var relearn_search_index=[{content:`En introduktion för utveckling, installation och drift.
`,description:"",tags:null,title:"Introduktion",uri:"/intro/index.html"},{content:`Innehåll Ursäkta röran. Vi bygger om …
`,description:"",tags:null,title:"Arkitektur",uri:"/architecture/index.html"},{content:`Dokumentation om drift och användning av våra ingående tjänster.
Context Broker `,description:"",tags:null,title:"Mikrotjänster",uri:"/services/index.html"},{content:`Information om hur du enklast kommer igång.
`,description:"",tags:null,title:"Komma igång",uri:"/getting-started/index.html"},{content:`Mer detaljerad information och konfigurationshjälp.
`,description:"",tags:null,title:"Konfiguration",uri:"/configuration/index.html"},{content:"",description:"",tags:null,title:"Categories",uri:"/categories/index.html"},{content:"",description:"",tags:null,title:"cip",uri:"/tags/cip/index.html"},{content:`Innehåll Ursäkta röran. Vi bygger om …
`,description:"",tags:null,title:"City Information Platform",uri:"/architecture/cip/index.html"},{content:`Test Ursäkta röran. Vi bygger om …
`,description:"",tags:["cip"],title:"Context Broker",uri:"/services/context-broker/index.html"},{content:`Om sakerna omkring dig kunde prata, vad skulle de säga?
Introduktion Diwise diwise är en IoT-kommunikationsplattform för att ta emot sensordata och reglera fysiska styrsystem som innebär att verksamhetssystem frikopplas från både kommunikationsgränssnitt och olika sensortyper.
Dokumentation Här på denna yta kommer vi publicera teknisk information samt dokumentation gällande plattformen Diwise.
Kontakt Behöver du komma i kontakt med oss eller vill du veta mer om vad vi kan erbjuda? Läs mer på vår webbplats, diwise.se.
`,description:"",tags:null,title:"Diwise",uri:"/index.html"},{content:`Innehåll Ursäkta röran. Vi bygger om …
`,description:"",tags:null,title:"IoT Platform",uri:"/architecture/iot/index.html"},{content:"",description:"",tags:null,title:"Tags",uri:"/tags/index.html"}]