baseURL = 'https://diwise.github.io/'
languageCode = 'en-us'
title = 'Diwise for Developers'
theme = 'hugo-theme-relearn'

# For search functionality
[outputs]
home = [ "HTML", "RSS", "SEARCH", "SEARCHPAGE"]
